/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MainContractAbi } from "./MainContractAbi";
export * as factories from "./factories";
export { MainContractAbi__factory } from "./factories/MainContractAbi__factory";
