import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import "../globals.css";
import { Web3Provider } from "@/contexts/web3Context";
import { ContractProvider } from "@/contexts/contractContext";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const messages = await getMessages({ locale });

  console.log("RootLayout Build at " + new Date().toISOString());
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`} id="body">
        <ThemeProvider attribute="data-theme" defaultTheme="dark" enableSystem>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <ContractProvider>
              <Web3Provider>
                {/* <div>Root layout</div> */}
                {children}
              </Web3Provider>
            </ContractProvider>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
